# H2
spring:
  h2:
    console:
      enabled: true
  # Datasource
  datasource:
    url: jdbc:h2:mem:crafty-study
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
